### ISSUE TITLE
Website is broken

### ISSUE THREAD

**Issue by mattlyons0** [nyellow/Mafia-Helper#1]
1. Website has invalid ssl cert
2. Website is default nginx configuration page

**Comment by mattlyons0** [comment]
Any reasoning for closing this? The website is now showing as the domain expired

**Comment by nyellow** [comment]
Are you typing in the [correct address?](https://www.zavoky.com/mafia)

**Comment by mattlyons0** [comment]
That link 404s

**Comment by nyellow** [comment]
Do you have a working internet connection?

**Comment by mattlyons0** [comment]
Nice you fixed it
